[package]
name = "nl_holidays"
version = "0.3.0"
edition = "2024"
description = "Dutch holidays"
repository = "https://github.com/daBlesr/nl-holidays-rs"
keywords = ["holidays"]
license = "MIT"

[dependencies]
chrono = { version = "0.4.*", default-features = false }